#!/bin/bash

set -e

wd=`pwd`

if [ -z "$LXC_GUEST_IP" ]; then
    LXC_GUEST_IP=10.0.3.5
fi

if [ -z "$LXC_BRIDGE" ]; then
    LXC_BRIDGE=lxcbr0
fi

if ifconfig $LXC_BRIDGE > /dev/null 2>&1; then
    true
else
    echo "Must configure $LXC_BRIDGE - check the README"
    exit 1
fi

sed "s;ROOTFS;$wd/target-$LXC_SUITE-$LXC_ARCH;;s;ARCH;$LXC_ARCH;g;;s;GUESTIP;$LXC_GUEST_IP;g;s;GUESTLINK;$LXC_BRIDGE;g" < etc/lxc.config.in > var/lxc.config
